### ISSUE TITLE
demonstration of "best practices"

### ISSUE THREAD

**Issue by jsms90** [Jbarget/handlebars-morning-challenge#16]
You mention that this isn't the way you would expect students' code to look:
> NB. I know the code isn't very dry but this is just for demonstration purposes!

But maybe the explanation could be a bit clearer, about why you have chosen not to make it dry? And/or maybe you could add a DRY branch, just to show what this would look like?

This is particularly timely, since there have been similar references in other workshops, and FAC10 have expressed frustration around being told "this is not the way you should do it", with no offering of how it should/could be done, or why mentors are doing it differently.

See number 5 under Go in [their latest stop go continue](https://github.com/foundersandcoders/london-curriculum/blob/d314f755712bed05c561c8ffa380255387519cec/stop-go-continue/fac-10/cohort-week-6.md#go), which was particularly in reference to [these lines](https://github.com/FAC9/postgres-workshop/blob/master/data.sql#L60-L61) in a postgres workshop, but apparently there have been others.

**Comment by Jbarget** [comment]
@jsms90 ive added a branch called `best-practice`. Let me know if you can spot anything there to fix

**Comment by Jbarget** [comment]
changed the name of branch `best-practice` to `dry`

**Comment by Jbarget** [comment]
@jsms90 can you close this unless you think ive missed something?
