### ISSUE TITLE
messages received when tests fail are very misleading 

### ISSUE THREAD

**Issue by mattlub** [Jbarget/handlebars-morning-challenge#17]
All 3 are misleading:
e.g. https://github.com/Jbarget/handlebars-morning-challenge/blob/master/test/test.js#L7
A much better message would be 'html should contain "Hello World: A bit of info about FAC!"'

Please change all of them, it was causing needless confusion.

**Comment by Jbarget** [comment]
haha completely fair enough

**Comment by Jbarget** [comment]
@mattlub let me know if theres changes i missed

**Comment by mattlub** [comment]
looks good
