### ISSUE TITLE
Need some explanation of what's going on

### ISSUE THREAD

**Issue by mattlub** [Jbarget/handlebars-morning-challenge#18]
Either some info in the readme or comments on these lines would be useful, otherwise people have no idea what the tests are testing, what the functions are doing etc.
https://github.com/Jbarget/handlebars-morning-challenge/blob/master/handlebars/handlebars.js#L4-L5

Maybe comments describing what the functions do would be useful as well, e.g:
'each function generates html from the template using the given context variables'

I know this may seem obvious but I think it is much better to explain stuff explicitly, when we saw this most people had no idea what was going on.

**Comment by Jbarget** [comment]
@mattlub that ok? If you think theres a clearer way of me doing it fo sho say

**Comment by mattlub** [comment]
yep all looks good. I guess maybe the readme could still do with a little bit of clearing up but I think now the code is clear.

**Comment by Jbarget** [comment]
@mattlub can you have a look over the readme and let me know if theres anything else that could do with a change?
