### ISSUE TITLE
context object name

### ISSUE THREAD

**Issue by mattlub** [Jbarget/handlebars-morning-challenge#19]
'obj' is a bad name imo, could be called context instead (this is more standard)- they call it context in the handlebars docs

https://github.com/Jbarget/handlebars-morning-challenge/blob/master/handlebars/handlebars.js#L8

**Comment by Jbarget** [comment]
👍

**Comment by Jbarget** [comment]
@mattlub the above commit all good?

**Comment by mattlub** [comment]
yep 👍
