### ISSUE TITLE
Extend the challenge with further reading about .hbs files

### ISSUE THREAD

**Issue by njsfield** [Jbarget/handlebars-morning-challenge#5]
Handlebars files have the extension .hbs, in this challenge, perhaps suggest changing the file format of message.html to message.hbs, that way you can use syntax highlighters specific to hbs files to easier readability, and change the source variable as follows;
```javascript
var source = fs.readFileSync(__dirname + "/message.hbs")
```

**Comment by Jbarget** [comment]
👍  good point
